<?php

/**
 * @file
 * migrate_example module file.
 */

/**
 * @defgroup migrate_example Example: Migrate
 * @ingroup examples
 * @{
 * A basic example of defining a migration through configuration YAML files and
 * custom source and process plugins.
 *
 * In this example we are performing three migrations: roles, users, content.
 * The source of the migration is proprietary hypothetical CMS into Drupal 8,
 * using the migrate API provided by the core Migrate module. The biggest part
 * of the migration is defined in the migration YAML files, placed under
 * 'config/' directory.
 *
 * However, migrate config files are not enough because we still need to
 * implement some migration plugins. The module implements a source plugin for
 * each migration and a process plugin for transforming the value to be
 * imported. Sandbox data is defined in migrate_example.install file and it's
 * used in tests provided by the module.
 *
 * Migrate examples provided by the module:
 *
 * - migrate_example_user_role: Migrates the source groups into Drupal roles.
 *   The source doesn't keep a separate table for groups, we are processing them
 *   from the people table.
 * - migrate_example_people: Migrates the list of users into Drupal. This
 *   migration request a simple custom process plugin 'explode' that expands the
 *   list of user groups from a semicolon delimited string to an array.
 * - migrate_example_content: Migrates the source articles into destination node
 *   entities of type 'page'. Note that the article author is migrated using the
 *   map of the previous users migration.
 *
 * How to test?
 *
 * There are three simpletest tests provided for each migration or you can
 * simply enable the module and run manually the migrations.
 * @}
 */
