id: node.pe_assignment_answer.default
uuid: daf8aab5-f77b-4c50-9003-030d527fedb2
targetEntityType: node
bundle: pe_assignment_answer
mode: default
content:
  field_assignment_question:
    type: entity_reference_label
    weight: '0'
    settings:
      link: 0
    label: above
  body:
    type: text_default
    weight: '1'
    settings: {  }
    label: above
  field_assignment_answer_file:
    type: file_default
    weight: '2'
    settings: {  }
    label: above
  field_score:
    type: integer
    weight: '3'
    settings:
      thousand_separator: ''
      prefix_suffix: 'TRUE'
    label: above
  field_remarks:
    type: text_default
    weight: '4'
    settings: {  }
    label: above
hidden:
  langcode: true
  field_ip_address: true
status: true
