id: node.pe_assignment_answer.teaser
uuid: effa2328-3737-4d31-ad00-df1d9d642557
targetEntityType: node
bundle: pe_assignment_answer
mode: teaser
content:
  field_assignment_question:
    type: entity_reference_label
    weight: '0'
    settings:
      link: 0
    label: above
  body:
    type: text_summary_or_trimmed
    weight: '1'
    settings:
      trim_length: '600'
    label: above
  field_assignment_answer_file:
    type: file_default
    weight: '2'
    settings: {  }
    label: above
hidden:
  langcode: true
  field_ip_address: true
  field_remarks: true
  field_score: true
status: true
