id: node.pe_assignment_answer.field_assignment_question
uuid: 11043a43-a6bf-4129-9a00-f728be2c9371
status: true
langcode: en
field_uuid: 73fd43cb-6f74-4354-943f-63f81f2d5f47
field_name: field_assignment_question
entity_type: node
bundle: pe_assignment_answer
label: Question
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  handler: default
  handler_settings:
    target_bundles:
      pe_assignment_question: pe_assignment_question
    sort:
      field: _none
field_type: entity_reference
