id: node.pe_assignment_answer.field_assignment_answer_file
uuid: 800f5929-57ed-46ff-9600-f94c155fb7ee
status: true
langcode: en
field_uuid: c064cf2d-c609-47d3-b300-ccad546d4733
field_name: field_assignment_answer_file
entity_type: node
bundle: pe_assignment_answer
label: 'Answer file'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  file_directory: ''
  file_extensions: 'txt odt doc docx xls xlsx ppt pptx pdf rtf'
  max_filesize: ''
  description_field: true
field_type: file
