id: node.field_academic_program_course
uuid: 68cbaa24-9c0a-4f14-9300-ee5d99f9b538
status: true
langcode: en
name: field_academic_program_course
entity_type: node
type: entity_reference
settings:
  target_type: node
module: entity_reference
locked: false
cardinality: 1
translatable: false
indexes: {  }
