id: node.field_ip_address
uuid: 3970ee98-33e1-457b-bb00-d34427c09b62
status: true
langcode: en
name: field_ip_address
entity_type: node
type: text
settings:
  max_length: 255
module: text
locked: false
cardinality: 1
translatable: false
indexes: {  }
