id: node.pe_assignment_question.default
uuid: d0182be5-349d-4583-9602-2db4ccc6d1b2
targetEntityType: node
bundle: pe_assignment_question
mode: default
content:
  body:
    type: text_default
    weight: '0'
    settings: {  }
    label: hidden
  field_academic_program_course:
    type: entity_reference_label
    weight: '1'
    settings:
      link: 0
    label: above
  field_max_score:
    type: integer
    weight: '2'
    settings:
      thousand_separator: ''
      prefix_suffix: 'TRUE'
    label: above
  field_pass_score:
    type: integer
    weight: '3'
    settings:
      thousand_separator: ''
      prefix_suffix: 'TRUE'
    label: above
  field_allow_uploads:
    type: list_default
    weight: '4'
    settings: {  }
    label: above
  field_percent:
    type: list_default
    weight: '5'
    settings: {  }
    label: above
  field_start_date:
    type: datetime_default
    weight: '6'
    settings:
      format_type: medium
    label: above
  field_end_date:
    type: datetime_default
    weight: '7'
    settings:
      format_type: medium
    label: above
  field_remarks:
    type: text_default
    weight: '8'
    settings: {  }
    label: above
hidden:
  langcode: true
status: true
