id: node.pe_assignment_question.default
uuid: 67bd9dba-3853-4f27-ae51-814f4d2593a8
targetEntityType: node
bundle: pe_assignment_question
mode: default
content:
  title:
    type: text_textfield
    weight: '0'
    settings:
      size: '60'
      placeholder: ''
  body:
    type: text_textarea_with_summary
    weight: '1'
    settings:
      rows: '9'
      summary_rows: '3'
      placeholder: ''
  field_academic_program_course:
    type: entity_reference_autocomplete
    weight: '2'
    settings:
      match_operator: CONTAINS
      size: 60
      autocomplete_type: single
      placeholder: ''
  field_max_score:
    type: number
    weight: '3'
    settings:
      placeholder: ''
  field_pass_score:
    type: number
    weight: '4'
    settings:
      placeholder: ''
  field_percent:
    type: options_buttons
    weight: '5'
    settings: {  }
  field_allow_uploads:
    type: options_buttons
    weight: '6'
    settings: {  }
  field_start_date:
    type: datetime_default
    weight: '7'
    settings: {  }
  field_end_date:
    type: datetime_default
    weight: '8'
    settings: {  }
  field_remarks:
    type: text_textarea
    weight: '9'
    settings:
      rows: '5'
      placeholder: ''
hidden: {  }
status: true
