id: node.pe_assignment_question.teaser
uuid: 99376020-825f-42a3-9f00-e9393d2c84fd
targetEntityType: node
bundle: pe_assignment_question
mode: teaser
content:
  body:
    type: text_summary_or_trimmed
    weight: '0'
    settings:
      trim_length: '600'
    label: hidden
  field_academic_program_course:
    type: entity_reference_label
    weight: '1'
    settings:
      link: 0
    label: above
  field_start_date:
    type: datetime_default
    weight: '2'
    settings:
      format_type: medium
    label: above
  field_end_date:
    type: datetime_default
    weight: '3'
    settings:
      format_type: medium
    label: above
hidden:
  langcode: true
  field_allow_uploads: true
  field_max_score: true
  field_pass_score: true
  field_percent: true
  field_remarks: true
status: true
