id: node.pe_assignment_question.field_percent
uuid: 43d42594-1147-40bc-9e5d-939e67781098
status: true
langcode: en
field_uuid: fcafd90a-f005-4f1d-b806-6a86b0fee8f1
field_name: field_percent
entity_type: node
bundle: pe_assignment_question
label: 'Percent?'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings: {  }
field_type: list_boolean
