id: node.pe_assignment_question.field_pass_score
uuid: f8332072-1d0d-448f-ad00-0a018e073d86
status: true
langcode: en
field_uuid: 05a80e13-be75-4988-9a00-f002ac995196
field_name: field_pass_score
entity_type: node
bundle: pe_assignment_question
label: 'Pass score'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  min: null
  max: null
  prefix: ''
  suffix: ''
field_type: integer
