id: node.pe_assignment_question.field_allow_uploads
uuid: ad356284-4671-4625-8500-ebdc9d696d2e
status: true
langcode: en
field_uuid: 09a47f81-26c8-4328-8d00-db4fbb0cea0b
field_name: field_allow_uploads
entity_type: node
bundle: pe_assignment_question
label: 'Allow uploads?'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings: {  }
field_type: list_boolean
