id: node.field_pass_score
uuid: 05a80e13-be75-4988-9a00-f002ac995196
status: true
langcode: en
name: field_pass_score
entity_type: node
type: integer
settings: {  }
module: Core
locked: false
cardinality: 1
translatable: false
indexes: {  }
