id: node.field_assignment_question
uuid: 73fd43cb-6f74-4354-943f-63f81f2d5f47
status: true
langcode: en
name: field_assignment_question
entity_type: node
type: entity_reference
settings:
  target_type: node
module: entity_reference
locked: false
cardinality: 1
translatable: false
indexes: {  }
