id: node.pe_assignment_question.field_end_date
uuid: 5c9eebdb-0876-4a71-b501-1b4168ebd466
status: true
langcode: en
field_uuid: 0fd4c4f1-886b-41cb-a001-01994ff55c51
field_name: field_end_date
entity_type: node
bundle: pe_assignment_question
label: 'End date'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings: {  }
field_type: datetime
