type: pe_assignment_question
uuid: f1ec2f2d-0505-492f-8b48-2e9b43b405e4
name: 'Assignment question'
description: 'Assignment or homework questions which are set as tasks for students.'
help: ''
has_title: true
title_label: Title
settings:
  node:
    preview: 1
    options:
      status: true
      promote: false
      sticky: false
      revision: false
    submitted: false
status: true
langcode: en
